### ISSUE TITLE
Sorting the slips by a signature number

### ISSUE THREAD

**Issue by Cyberolo** [ExLibrisGroup/Cloud-app-printing-multiple-slips-per-page#2]
Hi Ori. Your app is very useful for the libraries in Poland. They are asking about possibility of sorting the slips by a signature number. For a big academic libraries with huge closed stack it would be very helpful as the number of request is really big in academic year.
Signature is in alternative call number in Alma. 
Thank you in advance. 
Best regards.
Aleksander.

**Comment by ori229** [comment]
I'm glad to hear it is useful, but @Harel92 actually wrote the app. Thanks Harel!
Regarding soring - I'm afraid it is not possible because this app receives from Alma ready-to-print HTMLs 
(Using the API documented here: https://developers.exlibrisgroup.com/alma/apis/docs/tasklists/R0VUIC9hbG1hd3MvdjEvdGFzay1saXN0cy9wcmludG91dHM=/ )
It doesn't have access to the data of the request/item/etc. used to prepare the slip.

**Comment by Cyberolo** [comment]
Thank you for your answer and explanations. Congratulations to @Harel92 ! 
Best regards. 
Aleksander
